/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { BodyLoginUserLoginPostClientId } from './bodyLoginUserLoginPostClientId';
import type { BodyLoginUserLoginPostClientSecret } from './bodyLoginUserLoginPostClientSecret';
import type { BodyLoginUserLoginPostGrantType } from './bodyLoginUserLoginPostGrantType';

export interface BodyLoginUserLoginPost {
  client_id?: BodyLoginUserLoginPostClientId;
  client_secret?: BodyLoginUserLoginPostClientSecret;
  grant_type?: BodyLoginUserLoginPostGrantType;
  password: string;
  scope?: string;
  username: string;
}
