/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface CardInput {
  cardType: string;
  expiresAt: string;
  /**
   * @minLength 16
   * @maxLength 16
   */
  number: string;
}
