/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { CardType } from './cardType';

export interface CardOutput {
  cardType: CardType;
  expiresAt: string;
  id: number;
  isPrimary: boolean;
  number: string;
}
