/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type CardType = typeof CardType[keyof typeof CardType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CardType = {
  Uzcard: 'Uzcard',
  Humo: 'Humo',
  Visa: 'Visa',
  Mastercard: 'Mastercard',
} as const;
