/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface EditOrder {
  author: string;
  /** */
  categoryId: number;
  /** */
  deadline: number;
  orderId: number;
  price: number;
  skillsIds: number[];
  technicalTask: string;
  title: string;
}
