/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeOutput } from './employeeOutput';

export interface EmployeeResponse {
  createdAt: string;
  employee: EmployeeOutput;
  id: number;
  updatedAt: string;
}
