/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeOutputAbout } from './employeeOutputAbout';
import type { EmployeeOutputCardNumber } from './employeeOutputCardNumber';
import type { EmployeeOutputPhoneNumber } from './employeeOutputPhoneNumber';
import type { EmployeeOutputPortfolio } from './employeeOutputPortfolio';
import type { SkillOutput } from './skillOutput';

export interface EmployeeOutput {
  about?: EmployeeOutputAbout;
  balance: number;
  cardNumber?: EmployeeOutputCardNumber;
  createdAt: string;
  firstName: string;
  id: number;
  language: string;
  lastName: string;
  level: string;
  phoneNumber?: EmployeeOutputPhoneNumber;
  portfolio?: EmployeeOutputPortfolio;
  rating: number;
  skills?: SkillOutput[];
  telegramId: number;
  updatedAt: string;
}
