/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeOutputAbout } from './employeeOutputAbout';
import type { EmployeeOutputActiveOrder } from './employeeOutputActiveOrder';
import type { EmployeeOutputPhoneNumber } from './employeeOutputPhoneNumber';
import type { EmployeeOutputPortfolio } from './employeeOutputPortfolio';

export interface EmployeeOutput {
  about?: EmployeeOutputAbout;
  active_order?: EmployeeOutputActiveOrder;
  balance: number;
  createdAt: string;
  firstName: string;
  id: number;
  isVerified?: boolean;
  language: string;
  lastName: string;
  level: string;
  phoneNumber?: EmployeeOutputPhoneNumber;
  portfolio?: EmployeeOutputPortfolio;
  rating: number;
  telegramId: number;
  updatedAt: string;
}
