/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeActiveOrder } from './employeeActiveOrder';

export type EmployeeOutputActiveOrder = EmployeeActiveOrder | null;
