/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { OrderCategory } from './orderCategory';
import type { Currency } from './currency';
import type { DeadlineType } from './deadlineType';
import type { SkillOutput } from './skillOutput';
import type { OrderStatus } from './orderStatus';

export interface EmployeeActiveOrder {
  author: string;
  category: OrderCategory;
  createdAt: string;
  currency: Currency;
  deadline: number;
  deadlineType: DeadlineType;
  group: string;
  id: number;
  isExecutorSelected: boolean;
  price: number;
  skills: SkillOutput[];
  status: OrderStatus;
  technicalTask: string;
  title: string;
  updatedAt: string;
}
