/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { OrderCategory } from './orderCategory';

export type OrderOutputCategory = string | OrderCategory;
