/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { OrderCategory } from './orderCategory';

export interface OrderOutput {
  author: string;
  category: OrderCategory;
  createdAt: string;
  deadline: number;
  id: number;
  price: number;
  /**
   * @minLength 1
   * @maxLength 2083
   */
  technicalTask: string;
  title: string;
  updatedAt: string;
}
