/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { OrderOutput } from './orderOutput';

export interface OrderResponse {
  id: number;
  order: OrderOutput;
}
