/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterUser {
  /**
   * User email
   * @minLength 5
   * @maxLength 200
   */
  email: string;
  /**
   * User firstname
   * @minLength 1
   * @maxLength 50
   */
  firstname: string;
  /**
   * User lastname
   * @minLength 1
   * @maxLength 50
   */
  lastname: string;
  /**
   * User password
   * @minLength 6
   * @maxLength 50
   */
  password: string;
}
