/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface Token {
  /** Access Token */
  access_token: string;
  /** Expiration Date */
  expiresAt: number;
  /** Refresh Token */
  refresh_token: string;
  /** Token Type */
  type: string;
}
