/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
  income: 'income',
  withdrawal: 'withdrawal',
} as const;
