/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionType } from './transactionType';

export interface Transaction {
  amount: number;
  createdAt: string;
  id: number;
  type: TransactionType;
  updatedAt: string;
}
