/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  createdAt: string;
  email: string;
  firstname: string;
  id: number;
  lastname: string;
  updatedAt: string;
}
